route:
  receiver: 'alertmanager-logs'
  group_wait: 30s
  group_interval: 30s
  repeat_interval: 30s
  group_by: [alertname]

receivers:
- name: 'alertmanager-logs'
  webhook_configs:
  - url: 'http://host.docker.internal:3005/alerts'
    send_resolved: true